// Code generated by enum generator; DO NOT EDIT.

//nolint:stylecheck // allow non-camel-case for constants
package enums

type ErrorCode int32

// Error code values
const (
EC_NONE ErrorCode = 0 // No error (success).
EC_UNKNOWN ErrorCode = 1 // Unknown and unspecified error.
EC_SERVICE_COMMUNICATION_FAILED ErrorCode = 101 // Communication with service failed.
EC_IDENTITY_NOT_FOUND ErrorCode = 200 // Ego not found.
EC_IDENTITY_NAME_CONFLICT ErrorCode = 201 // Identifier already in use for another ego.
EC_IDENTITY_INVALID ErrorCode = 202 // The given ego is invalid or malformed.
EC_NAMESTORE_UNKNOWN ErrorCode = 5000 // Unknown namestore error.
EC_NAMESTORE_ITERATION_FAILED ErrorCode = 5001 // Zone iteration failed.
EC_NAMESTORE_ZONE_NOT_FOUND ErrorCode = 5002 // Zone not found.
EC_NAMESTORE_RECORD_NOT_FOUND ErrorCode = 5003 // Record not found.
EC_NAMESTORE_RECORD_DELETE_FAILED ErrorCode = 5004 // Zone iteration failed.
EC_NAMESTORE_ZONE_EMPTY ErrorCode = 5005 // Zone does not contain any records.
EC_NAMESTORE_LOOKUP_ERROR ErrorCode = 5006 // Failed to lookup record.
EC_NAMESTORE_NO_RECORDS_GIVEN ErrorCode = 5007 // No records given.
EC_NAMESTORE_RECORD_DATA_INVALID ErrorCode = 5008 // Record data invalid.
EC_NAMESTORE_NO_LABEL_GIVEN ErrorCode = 5009 // No label given.
EC_NAMESTORE_NO_RESULTS ErrorCode = 5010 // No results given.
EC_NAMESTORE_RECORD_EXISTS ErrorCode = 5011 // Record already exists.
EC_NAMESTORE_RECORD_TOO_BIG ErrorCode = 5012 // Record size exceeds maximum limit.
EC_NAMESTORE_BACKEND_FAILED ErrorCode = 5013 // There was an error in the database backend.
EC_NAMESTORE_STORE_FAILED ErrorCode = 5014 // Failed to store the given records.
EC_NAMESTORE_LABEL_INVALID ErrorCode = 5015 // Label invalid or malformed.

)
