// Code generated by enum generator; DO NOT EDIT.

package enums

type BlockType int

// DHT block types
const (
{{ range $i, $kv := . }}BLOCK_TYPE_{{.Name}} BlockType = {{.Number}} // {{.Comment}}
{{ end }}
)

