// Code generated by enum generator; DO NOT EDIT.

package enums

type SigPurpose int

// Signature purpose values
const (
{{ range $i, $kv := . }}SIG_{{.Name}} SigPurpose = {{.Number}} // {{.Comment}}
{{ end }}
)
