// Code generated by enum generator; DO NOT EDIT.

//nolint:stylecheck // allow non-camel-case for constants
package enums

//----------------------------------------------------------------------
// Resource Record Flags
//----------------------------------------------------------------------

// GNSFlag type
type GNSFlag uint16

const (
	// GNS record flags
{{ range $i, $kv := . }}
	GNS_FLAG_{{.Name}} GNSFlag = (1<<(15-{{.Number}})) // {{.Comment}}
{{ end }}
)

// List flags as strings
func (gf GNSFlag) List() (flags []string) {
	if gf&GNS_FLAG_PRIVATE != 0 {
		flags = append(flags, "Private")
	}
	if gf&GNS_FLAG_SHADOW != 0 {
		flags = append(flags, "Shadow")
	}
	if gf&GNS_FLAG_SUPPLEMENTAL != 0 {
		flags = append(flags, "Suppl")
	}
	if gf&GNS_FLAG_CRITICAL != 0 {
		flags = append(flags, "Critical")
	}
	if gf&GNS_FLAG_RELATIVE_EXPIRATION != 0 {
		flags = append(flags, "TTL")
	}
	return
}
