// Code generated by enum generator; DO NOT EDIT.

//nolint:stylecheck // allow non-camel-case for constants
package enums

type ErrorCode uint32

// Error code values
const (
{{ range $i, $kv := . }}EC_{{.Name}} ErrorCode = {{.Value}} // {{.Description}}
{{ end }}
)
