// Code generated by "stringer -type=SigPurpose signature_purpose.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SIG_TEST-0]
	_ = x[SIG_TRANSPORT_PONG_OWN-1]
	_ = x[SIG_TRANSPORT_DISCONNECT-2]
	_ = x[SIG_REVOCATION-3]
	_ = x[SIG_NAMESPACE_ADVERTISEMENT-4]
	_ = x[SIG_PEER_PLACEMENT-5]
	_ = x[SIG_DHT_HOP-6]
	_ = x[SIG_HELLO-7]
	_ = x[SIG_DNS_RECORD-11]
	_ = x[SIG_CHAT_MESSAGE-12]
	_ = x[SIG_CHAT_RECEIPT-13]
	_ = x[SIG_NSE_SEND-14]
	_ = x[SIG_GNS_RECORD_SIGN-15]
	_ = x[SIG_SET_ECC_KEY-16]
	_ = x[SIG_FS_UBLOCK-17]
	_ = x[SIG_REGEX_ACCEPT-18]
	_ = x[SIG_CONVERSATION_RING-20]
	_ = x[SIG_SECRETSHARING_DKG1-21]
	_ = x[SIG_SECRETSHARING_DKG2-22]
	_ = x[SIG_SECRETSHARING_DECRYPTION-23]
	_ = x[SIG_RECLAIM_CODE_SIGN-27]
	_ = x[SIG_DELEGATE-28]
	_ = x[SIG_TRANSPORT_ADDRESS-29]
	_ = x[SIG_TRANSPORT_EPHEMERAL-30]
	_ = x[SIG_COMMUNICATOR_TCP_HANDSHAKE-31]
	_ = x[SIG_COMMUNICATOR_TCP_REKEY-32]
	_ = x[SIG_COMMUNICATOR_UDP_HANDSHAKE-33]
	_ = x[SIG_COMMUNICATOR_UDP_BROADCAST-34]
	_ = x[SIG_TRANSPORT_CHALLENGE-35]
	_ = x[SIG_TRANSPORT_DV_HOP-36]
	_ = x[SIG_TRANSPORT_DV_INITIATOR-37]
	_ = x[SIG_CADET_CONNECTION_INITIATOR-38]
}

const (
	_SigPurpose_name_0 = "SIG_TESTSIG_TRANSPORT_PONG_OWNSIG_TRANSPORT_DISCONNECTSIG_REVOCATIONSIG_NAMESPACE_ADVERTISEMENTSIG_PEER_PLACEMENTSIG_DHT_HOPSIG_HELLO"
	_SigPurpose_name_1 = "SIG_DNS_RECORDSIG_CHAT_MESSAGESIG_CHAT_RECEIPTSIG_NSE_SENDSIG_GNS_RECORD_SIGNSIG_SET_ECC_KEYSIG_FS_UBLOCKSIG_REGEX_ACCEPT"
	_SigPurpose_name_2 = "SIG_CONVERSATION_RINGSIG_SECRETSHARING_DKG1SIG_SECRETSHARING_DKG2SIG_SECRETSHARING_DECRYPTION"
	_SigPurpose_name_3 = "SIG_RECLAIM_CODE_SIGNSIG_DELEGATESIG_TRANSPORT_ADDRESSSIG_TRANSPORT_EPHEMERALSIG_COMMUNICATOR_TCP_HANDSHAKESIG_COMMUNICATOR_TCP_REKEYSIG_COMMUNICATOR_UDP_HANDSHAKESIG_COMMUNICATOR_UDP_BROADCASTSIG_TRANSPORT_CHALLENGESIG_TRANSPORT_DV_HOPSIG_TRANSPORT_DV_INITIATORSIG_CADET_CONNECTION_INITIATOR"
)

var (
	_SigPurpose_index_0 = [...]uint8{0, 8, 30, 54, 68, 95, 113, 124, 133}
	_SigPurpose_index_1 = [...]uint8{0, 14, 30, 46, 58, 77, 92, 105, 121}
	_SigPurpose_index_2 = [...]uint8{0, 21, 43, 65, 93}
	_SigPurpose_index_3 = [...]uint16{0, 21, 33, 54, 77, 107, 133, 163, 193, 216, 236, 262, 292}
)

func (i SigPurpose) String() string {
	switch {
	case i <= 7:
		return _SigPurpose_name_0[_SigPurpose_index_0[i]:_SigPurpose_index_0[i+1]]
	case 11 <= i && i <= 18:
		i -= 11
		return _SigPurpose_name_1[_SigPurpose_index_1[i]:_SigPurpose_index_1[i+1]]
	case 20 <= i && i <= 23:
		i -= 20
		return _SigPurpose_name_2[_SigPurpose_index_2[i]:_SigPurpose_index_2[i+1]]
	case 27 <= i && i <= 38:
		i -= 27
		return _SigPurpose_name_3[_SigPurpose_index_3[i]:_SigPurpose_index_3[i+1]]
	default:
		return "SigPurpose(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
